 

"use strict";

 
const JAVASCRIPT_MODULE_TYPE_AUTO = "javascript/auto";

 
const JAVASCRIPT_MODULE_TYPE_DYNAMIC = "javascript/dynamic";

 
const JAVASCRIPT_MODULE_TYPE_ESM = "javascript/esm";

 
const JSON_MODULE_TYPE = "json";

 
const WEBASSEMBLY_MODULE_TYPE_ASYNC = "webassembly/async";

 
const WEBASSEMBLY_MODULE_TYPE_SYNC = "webassembly/sync";

 
const CSS_MODULE_TYPE = "css";
 
const CSS_MODULE_TYPE_GLOBAL = "css/global";
 
const CSS_MODULE_TYPE_MODULE = "css/module";

 
const CSS_MODULE_TYPE_AUTO = "css/auto";

 
const ASSET_MODULE_TYPE = "asset";

 
const ASSET_MODULE_TYPE_INLINE = "asset/inline";

 
const ASSET_MODULE_TYPE_RESOURCE = "asset/resource";

 
const ASSET_MODULE_TYPE_SOURCE = "asset/source";

 
const ASSET_MODULE_TYPE_RAW_DATA_URL = "asset/raw-data-url";

 
const WEBPACK_MODULE_TYPE_RUNTIME = "runtime";
 
const WEBPACK_MODULE_TYPE_FALLBACK = "fallback-module";
 
const WEBPACK_MODULE_TYPE_REMOTE = "remote-module";

 
const WEBPACK_MODULE_TYPE_PROVIDE = "provide-module";


const WEBPACK_MODULE_TYPE_CONSUME_SHARED_MODULE = "consume-shared-module";


const WEBPACK_MODULE_TYPE_LAZY_COMPILATION_PROXY = "lazy-compilation-proxy";
 
module.exports.ASSET_MODULE_TYPE = ASSET_MODULE_TYPE;
module.exports.ASSET_MODULE_TYPE_RAW_DATA_URL = ASSET_MODULE_TYPE_RAW_DATA_URL;
module.exports.ASSET_MODULE_TYPE_SOURCE = ASSET_MODULE_TYPE_SOURCE;
module.exports.ASSET_MODULE_TYPE_RESOURCE = ASSET_MODULE_TYPE_RESOURCE;
module.exports.ASSET_MODULE_TYPE_INLINE = ASSET_MODULE_TYPE_INLINE;
module.exports.JAVASCRIPT_MODULE_TYPE_AUTO = JAVASCRIPT_MODULE_TYPE_AUTO;
module.exports.JAVASCRIPT_MODULE_TYPE_DYNAMIC = JAVASCRIPT_MODULE_TYPE_DYNAMIC;
module.exports.JAVASCRIPT_MODULE_TYPE_ESM = JAVASCRIPT_MODULE_TYPE_ESM;
module.exports.JSON_MODULE_TYPE = JSON_MODULE_TYPE;
module.exports.WEBASSEMBLY_MODULE_TYPE_ASYNC = WEBASSEMBLY_MODULE_TYPE_ASYNC;
module.exports.WEBASSEMBLY_MODULE_TYPE_SYNC = WEBASSEMBLY_MODULE_TYPE_SYNC;
module.exports.CSS_MODULE_TYPE = CSS_MODULE_TYPE;
module.exports.CSS_MODULE_TYPE_GLOBAL = CSS_MODULE_TYPE_GLOBAL;
module.exports.CSS_MODULE_TYPE_MODULE = CSS_MODULE_TYPE_MODULE;
module.exports.CSS_MODULE_TYPE_AUTO = CSS_MODULE_TYPE_AUTO;
module.exports.WEBPACK_MODULE_TYPE_RUNTIME = WEBPACK_MODULE_TYPE_RUNTIME;
module.exports.WEBPACK_MODULE_TYPE_FALLBACK = WEBPACK_MODULE_TYPE_FALLBACK;
module.exports.WEBPACK_MODULE_TYPE_REMOTE = WEBPACK_MODULE_TYPE_REMOTE;
module.exports.WEBPACK_MODULE_TYPE_PROVIDE = WEBPACK_MODULE_TYPE_PROVIDE;
module.exports.WEBPACK_MODULE_TYPE_CONSUME_SHARED_MODULE =
	WEBPACK_MODULE_TYPE_CONSUME_SHARED_MODULE;
module.exports.WEBPACK_MODULE_TYPE_LAZY_COMPILATION_PROXY =
	WEBPACK_MODULE_TYPE_LAZY_COMPILATION_PROXY;
